### ISSUE TITLE
react native compatible?

### ISSUE THREAD

**Issue by ddikodroid** [revelcw/react-hooks-helper#26]
can i use this package in react native project?

**Comment by revelcw** [comment]
I'm so sorry I couldn't get to you in time.

Yes! It can. Because hooks don't do any rendering it will work with React Native.

For example, `useSstep` just passes back functions to call, so it will work if you react React Native rendering. UseStep *doesn't* give you a `<Carousel />` component that has `<div>` and `<spans>`inside it (instead of `<View>` and `<Text>` ig).
```javascript
const { isPaused, index, step, navigation } = useStep(config);
```
